/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se2.ideafactory.view;

import java.awt.print.PrinterException;
import java.io.File;
import java.text.MessageFormat;
import java.util.Hashtable;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import se2.ideafactory.model.GeneticAlgorothm;
import se2.ideafactory.model.PreferenceTable;
import se2.ideafactory.model.SimulatedAnealing;
import se2.ideafactory.model.TempDataWriteToXML;

/**
 *
 * @author Sandharu1
 */
public class MainJFrame extends javax.swing.JFrame {

    Hashtable solution;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        jSaveBtn.setEnabled(false);
        jCancelBtn.setEnabled(false);
        jPrintBtn.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jBrowseTF = new javax.swing.JTextField();
        jBrowseBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        browseWarningLable = new javax.swing.JLabel();
        jPathWarningLable = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSARadioBtn = new javax.swing.JRadioButton();
        jGARadioBtn = new javax.swing.JRadioButton();
        jGenarateBtn = new javax.swing.JButton();
        jCancelBtn = new javax.swing.JButton();
        jHelpBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPasscode = new javax.swing.JPasswordField();
        jWarningLabel = new javax.swing.JLabel();
        jPreviewScrollPane = new javax.swing.JScrollPane();
        jXPreviewTbl = new org.jdesktop.swingx.JXTable();
        jSaveBtn = new javax.swing.JButton();
        jPrintBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Project Allocation System  - IdeaFactory");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(600, 730));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 730));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(240, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        jPanel3.setMinimumSize(new java.awt.Dimension(450, 91));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Upload Data File:");

        jBrowseTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        jBrowseTF.setCaretColor(new java.awt.Color(0, 51, 51));
        jBrowseTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrowseTFActionPerformed(evt);
            }
        });

        jBrowseBtn.setBackground(new java.awt.Color(204, 204, 255));
        jBrowseBtn.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jBrowseBtn.setForeground(new java.awt.Color(0, 0, 153));
        jBrowseBtn.setText("Browse");
        jBrowseBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        jBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrowseBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("*you can only upload .tsv fle with valid format.");

        browseWarningLable.setForeground(new java.awt.Color(255, 0, 0));
        browseWarningLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPathWarningLable.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jPathWarningLable.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jPathWarningLable, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBrowseTF, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseWarningLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBrowseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBrowseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jBrowseTF)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(browseWarningLable)
                    .addComponent(jPathWarningLable))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(70, 160, 450, 91);

        jPanel2.setBackground(new java.awt.Color(240, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Select Algorithm:");

        jSARadioBtn.setBackground(new java.awt.Color(240, 255, 255));
        buttonGroup1.add(jSARadioBtn);
        jSARadioBtn.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jSARadioBtn.setForeground(new java.awt.Color(0, 102, 204));
        jSARadioBtn.setSelected(true);
        jSARadioBtn.setText("Simulated Annealing Algorithm");
        jSARadioBtn.setName("b11"); // NOI18N
        jSARadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSARadioBtnActionPerformed(evt);
            }
        });

        jGARadioBtn.setBackground(new java.awt.Color(240, 255, 255));
        buttonGroup1.add(jGARadioBtn);
        jGARadioBtn.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jGARadioBtn.setForeground(new java.awt.Color(0, 102, 204));
        jGARadioBtn.setText("Genetic Algorithm");

        jGenarateBtn.setBackground(new java.awt.Color(153, 204, 255));
        jGenarateBtn.setFont(new java.awt.Font("Microsoft Tai Le", 1, 11)); // NOI18N
        jGenarateBtn.setForeground(new java.awt.Color(0, 51, 204));
        jGenarateBtn.setText("Generate");
        jGenarateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jGenarateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenarateBtnActionPerformed(evt);
            }
        });

        jCancelBtn.setBackground(new java.awt.Color(153, 204, 255));
        jCancelBtn.setFont(new java.awt.Font("Microsoft Tai Le", 1, 11)); // NOI18N
        jCancelBtn.setForeground(new java.awt.Color(153, 0, 0));
        jCancelBtn.setText("Cancel");
        jCancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelBtnActionPerformed(evt);
            }
        });

        jHelpBtn.setBackground(new java.awt.Color(153, 204, 255));
        jHelpBtn.setFont(new java.awt.Font("Microsoft Tai Le", 1, 11)); // NOI18N
        jHelpBtn.setForeground(new java.awt.Color(0, 153, 0));
        jHelpBtn.setText("Help");
        jHelpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jHelpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHelpBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Secure Pass Code:");

        jPasscode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        jPasscode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasscodeKeyTyped(evt);
            }
        });

        jWarningLabel.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jWarningLabel.setForeground(new java.awt.Color(255, 0, 0));
        jWarningLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jGenarateBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(121, 121, 121))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSARadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jGARadioBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jHelpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jWarningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasscode, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jPasscode, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSARadioBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jWarningLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jGARadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGenarateBtn)
                    .addComponent(jCancelBtn)
                    .addComponent(jHelpBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(70, 270, 450, 126);

        jXPreviewTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "#", "Student", "Project Title"
            }
        ));
        jXPreviewTbl.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jPreviewScrollPane.setViewportView(jXPreviewTbl);

        jPanel1.add(jPreviewScrollPane);
        jPreviewScrollPane.setBounds(70, 440, 450, 150);

        jSaveBtn.setBackground(new java.awt.Color(153, 204, 255));
        jSaveBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jSaveBtn.setForeground(new java.awt.Color(0, 51, 204));
        jSaveBtn.setText("Save As");
        jSaveBtn.setBorder(null);
        jSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(jSaveBtn);
        jSaveBtn.setBounds(90, 600, 170, 30);

        jPrintBtn.setBackground(new java.awt.Color(153, 204, 255));
        jPrintBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jPrintBtn.setForeground(new java.awt.Color(0, 51, 204));
        jPrintBtn.setText("Print");
        jPrintBtn.setBorder(null);
        jPrintBtn.setMinimumSize(new java.awt.Dimension(45, 17));
        jPrintBtn.setPreferredSize(new java.awt.Dimension(45, 17));
        jPrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrintBtnActionPerformed(evt);
            }
        });
        jPanel1.add(jPrintBtn);
        jPrintBtn.setBounds(340, 600, 160, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PREVIEW");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 410, 470, 230);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jframeBackWithLogo.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSARadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSARadioBtnActionPerformed
        // TODO add your handlng code here:
    }//GEN-LAST:event_jSARadioBtnActionPerformed


    private void jGenarateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenarateBtnActionPerformed
        // TODO add your handling code here:
        //Actions validation using buttons.
        String[][] row = new String[200][2];
        jGenarateBtn.setEnabled(false);
        jSaveBtn.setEnabled(true);
        jCancelBtn.setEnabled(true);
        jPrintBtn.setEnabled(true);

        //Get algorithm selection
//        JRadioButton selectedButton = null;
//
//        String choice = selectedButton.getText();
//        System.out.println("radioBtn: " + choice);

        //Check passcode from user
        String textFieldValue = jPasscode.getText();
        String pathValue = jBrowseTF.getText();
        if (textFieldValue.equals("demo")) { //if pass-code is correct
            jWarningLabel.setText("Completed");
            if (!pathValue.equals("")) {   // If tsv path is correct
                //call implementation of logic

                String importpath = jBrowseTF.getText(); //import file path
                System.out.println("import path: " + importpath);
                PreferenceTable preferenceTable = new PreferenceTable(importpath);
                preferenceTable.fillPreferencesOfAll(10);

                //------Simulated Annealing-------
                if (jSARadioBtn.isSelected()) { //Get SA algorithm selection
                    SimulatedAnealing sa = new SimulatedAnealing(preferenceTable, 10);
                    sa.getSolution();//Final answer-hashtable
                    sa.displayBestSol();
                    solution = sa.getSolution();
                    //Get SA data to priview table data
                    Hashtable<Integer, String> hashTableObject = sa.getSolution();
                    int temp = 0;
                    Set set = hashTableObject.entrySet();
                    Iterator it = set.iterator();
                    while (it.hasNext()) {
                        Map.Entry entry = (Map.Entry) it.next();
                        row[temp][0] = entry.getKey() + "";
                        row[temp++][1] = entry.getValue() + "";
                    }
                }
                //------Genetic Algorithm-------
                if (jGARadioBtn.isSelected()) { //Get GA algorithm selection
                    GeneticAlgorothm ga = new GeneticAlgorothm(preferenceTable);
                    ga.getSolution();//Final answer-hashtable
                    ga.displayBestSol();
                    solution = ga.getSolution();
                    
                    //Get GA data to priview table data
                    Hashtable<Integer, String> hashTableObject = ga.getSolution();
                    int temp = 0;
                    Set set = hashTableObject.entrySet();
                    Iterator it = set.iterator();
                    while (it.hasNext()) {
                        Map.Entry entry = (Map.Entry) it.next();
                        row[temp][0] = entry.getKey() + "";
                        row[temp++][1] = entry.getValue() + "";
                    }
                }

//                SimulatedAnealing sa = new SimulatedAnealing(preferenceTable, 100);
//                sa.displayBestSol();
//                solution = sa.getSolution();
            }
        }
        if (pathValue.equals("")) {  // If path is incorrect
            jPathWarningLable.setText("ERROR: Invalid Path");
            jBrowseTF.setText("");
        }
        //if pass code if wrong
        if (!textFieldValue.equals("demo")) { //If Pass-code is incorrect
            jWarningLabel.setText("ERROR: Invalid Passcode");
            jPasscode.setText("");
        }
        System.out.println("passcode: " + textFieldValue);

        //Send data to priview table
        DefaultTableModel model = (DefaultTableModel) jXPreviewTbl.getModel();
        model.addRow(row);
        DefaultTableModel dtm = new DefaultTableModel((new Object[]{"#", "Student Name", "Project Title"}), 0);
        jXPreviewTbl.setModel(dtm);
        Iterator<String> it = solution.keySet().iterator();
        String name, project;
        int temp = 0;
        while (it.hasNext()) {
            String sname = it.next();
            //String project = solution.get(sname).getAssignedProject();
            name = row[temp][0];
            project = row[temp++][1];
            dtm.addRow(new Object[]{temp, name, project});
            //System.out.println("table print test: "+temp+" - "+name+" - "+project);
        }
        jXPreviewTbl.packAll(); //wrap content of preview table
    }//GEN-LAST:event_jGenarateBtnActionPerformed

    private void jCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelBtnActionPerformed
        // TODO add your handling code here:
        //Actions validation using buttons.
        jGenarateBtn.setEnabled(true);
        jSaveBtn.setEnabled(false);
        jPrintBtn.setEnabled(false);
        jPrintBtn.setEnabled(false);
        jCancelBtn.setEnabled(false);
        jWarningLabel.setText("");
        jBrowseTF.setText("");
        jPasscode.setText("");
        jPathWarningLable.setText("");

    }//GEN-LAST:event_jCancelBtnActionPerformed

    private void jSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveBtnActionPerformed
        // TODO add your handling code here:
        //File save with XML & Tsv file filter
        FileFilter filter = new FileNameExtensionFilter("XML File", "xml");
        FileFilter filter2 = new FileNameExtensionFilter("TSV File", "tsv");
        JFileChooser chooser = new JFileChooser();
        //chooser.addChoosableFileFilter(filter);
        chooser.setFileFilter(filter2);
        chooser.setFileFilter(filter);
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.showSaveDialog(null);
        File dataFile = chooser.getSelectedFile();
        String ext = ((FileNameExtensionFilter) chooser.getFileFilter()).getExtensions()[0]; //get selected extention
        //System.out.println("selected extention: "+ext);
        String fileName = dataFile.getAbsolutePath();
        TempDataWriteToXML write = new TempDataWriteToXML();
        write.setHashTable(solution); //tempary call hash
        // write.getRows(); //tempary call hash
        //check file extention and call specific file write
        if (ext.equals("xml")) {
            write.writeToXmlFile(fileName); //call xml write
        }
        if (ext.equals("tsv")) {
            System.out.println(fileName);
            write.writeToCsvFile(fileName); // call tsv write
        }
    }//GEN-LAST:event_jSaveBtnActionPerformed

    private void jHelpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHelpBtnActionPerformed
        // TODO add your handling code here:
        //default title and icon
        JOptionPane.showMessageDialog(null, "Stochastic Project Allocation System\n" +
"\n" +
"Basic process\n" +
"\n" +
"1.	User should give the “.tsv” data file path with valid format.\n" +
"2.	Select algorithm by user choice.\n" +
"3.	Type secure pass code. (Contact admin to get it)\n" +
"4.	Click generate button to generate the report.\n" +
"5.	Click Cancel button to clear all the process.\n" +
"\n" +
"Save File\n" +
"1. After generate allocation file you can save it on your local machine by clicking Save As button.\n" +
" Save file types: XML, TSV\n" +
"\n" +
"Print Data\n" +
"1. You can print the allocation file directly without saving it by clicking Print button.\n" +
"\n" +
"__Contact IdeaFactory Help & Support Center for more..__", "IdeaFactory - Help Center", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jHelpBtnActionPerformed

    private void jBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrowseBtnActionPerformed
        // TODO add your handling code here:
        //file chooser with spreadsheet file filter
        FileFilter filter = new FileNameExtensionFilter("TSV File", "tsv", "csv");
        JFileChooser chooser = new JFileChooser();
        //chooser.addChoosableFileFilter(filter);
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(null);
        File dataFile = chooser.getSelectedFile();
        String fileName = dataFile.getAbsolutePath();
        jBrowseTF.setText(fileName);
    }//GEN-LAST:event_jBrowseBtnActionPerformed

    private void jPasscodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasscodeKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_jPasscodeKeyTyped

    private void jBrowseTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrowseTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBrowseTFActionPerformed

    private void jPrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrintBtnActionPerformed
        // TODO add your handling code here:
        //Print jtable preview directly using system printers
        MessageFormat header = new MessageFormat("Stochastic Project Allocation");
        MessageFormat footer = new MessageFormat("--IdeaFactory--                           page {0}");
        try {
            /* print the table */
            boolean complete = jXPreviewTbl.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);

            /* if printing completes */
            if (complete) {
                /* show a success message */
                JOptionPane.showMessageDialog(this,
                        "Printing Complete",
                        "Printing Result",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                /* show a message indicating that printing was cancelled */
                JOptionPane.showMessageDialog(this,
                        "Printing Cancelled",
                        "Printing Result",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (PrinterException pe) {
            /* Printing failed, report to the user */
            JOptionPane.showMessageDialog(this,
                    "Printing Failed: " + pe.getMessage(),
                    "Printing Result",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jPrintBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel browseWarningLable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBrowseBtn;
    private javax.swing.JTextField jBrowseTF;
    private javax.swing.JButton jCancelBtn;
    private javax.swing.JRadioButton jGARadioBtn;
    private javax.swing.JButton jGenarateBtn;
    private javax.swing.JButton jHelpBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasscode;
    private javax.swing.JLabel jPathWarningLable;
    private javax.swing.JScrollPane jPreviewScrollPane;
    private javax.swing.JButton jPrintBtn;
    private javax.swing.JRadioButton jSARadioBtn;
    private javax.swing.JButton jSaveBtn;
    private javax.swing.JLabel jWarningLabel;
    private org.jdesktop.swingx.JXTable jXPreviewTbl;
    // End of variables declaration//GEN-END:variables
}
